In [1]:
from amrafile import amrafile as af

In [12]:
testSignal = af.parse('/moria/data/DB/0064/00025/wholebody_normalized_water_1_00025.amra')

In [3]:
prototypePath = '/home/hannes/DB/0030/0015E/prototypes'

In [4]:
from os import listdir

In [5]:
import os

In [6]:
from os.path import isfile, join

In [7]:
prototypes = [join(prototypePath,f) for f in listdir(prototypePath)  if isfile(join(prototypePath, f))]

In [8]:
prototypeSignals = []
for prototype in prototypes:
    prototypeSignals.append(af.parse(prototype))
    

In [9]:
prototypesT9 = []
for signal in prototypeSignals:
    prototypesT9.append(signal.get_poi('T9'))

In [10]:
import numpy as np

In [11]:
prototypeData = np.array(prototypesT9)

In [3]:
testSignal.voxel_size()

(2.9959349632263184, 2.2299745082855225, 2.227569580078125)

In [19]:
prototypeSignals[0].voxel_size()

(3.2223719081213305, 2.2321429252624512, 2.2321429252624512)

In [14]:
T9 = signal.get_poi('T9')

In [13]:
testSignal.get_pois()

[((170, 95, 154), 'LeftFemur'),
 ((172, 93, 68), 'RightFemur'),
 ((196, 108, 111), 'S1'),
 ((210, 101, 111), 'L5'),
 ((222, 102, 112), 'L4'),
 ((234, 105, 111), 'L3'),
 ((246, 108, 111), 'L2'),
 ((256, 111, 112), 'L1'),
 ((267, 113, 112), 'T12'),
 ((276, 114, 112), 'T11'),
 ((285, 115, 112), 'T10'),
 ((292, 117, 113), 'T9'),
 ((334, 70, 114), 'Manubrium'),
 ((344, 85, 27), 'RightHumerus'),
 ((350, 91, 196), 'LeftHumerus')]

In [15]:
T9

(263, 120, 100)

In [16]:
signal.data.shape

(344, 174, 224)

In [17]:
prototypesT9

[(268, 116, 95),
 (272, 122, 97),
 (263, 113, 99),
 (261, 118, 98),
 (273, 125, 100),
 (269, 124, 100),
 (268, 122, 101),
 (258, 124, 96),
 (267, 119, 101),
 (259, 126, 101),
 (267, 124, 99),
 (255, 126, 102),
 (275, 128, 102),
 (268, 122, 100),
 (263, 123, 102),
 (266, 123, 97),
 (270, 121, 100),
 (266, 120, 99),
 (264, 120, 102),
 (269, 119, 97),
 (262, 116, 96),
 (267, 125, 101),
 (262, 120, 100),
 (268, 128, 100),
 (268, 119, 101),
 (266, 118, 99),
 (261, 124, 97),
 (261, 119, 99),
 (263, 120, 100)]

In [18]:
np.var(prototypesT9,axis = 1)

array([ 5941.55555556,  5972.22222222,  5510.22222222,  5268.66666667,
        5828.66666667,  5573.55555556,  5516.22222222,  4998.22222222,
        5531.55555556,  4808.66666667,  5477.55555556,  4514.        ,
        5801.55555556,  5558.22222222,  5106.88888889,  5520.66666667,
        5726.88888889,  5516.22222222,  5256.        ,  5840.88888889,
        5474.66666667,  5366.22222222,  5200.88888889,  5400.88888889,
        5601.55555556,  5572.66666667,  5154.88888889,  5200.88888889,
        5268.66666667])

In [19]:
np.var(np.array(prototypesT9),axis = 1)

array([ 5941.55555556,  5972.22222222,  5510.22222222,  5268.66666667,
        5828.66666667,  5573.55555556,  5516.22222222,  4998.22222222,
        5531.55555556,  4808.66666667,  5477.55555556,  4514.        ,
        5801.55555556,  5558.22222222,  5106.88888889,  5520.66666667,
        5726.88888889,  5516.22222222,  5256.        ,  5840.88888889,
        5474.66666667,  5366.22222222,  5200.88888889,  5400.88888889,
        5601.55555556,  5572.66666667,  5154.88888889,  5200.88888889,
        5268.66666667])

In [20]:
np.var(np.array(prototypesT9),axis = 0)

array([ 20.24970273,  12.80142687,   3.81212842])

In [21]:
prototypesLF = []
for signal in prototypeSignals:
    prototypesLF.append(signal.get_poi('LeftFemur'))

In [22]:
np.var(np.array(prototypesLF),axis = 0)

array([ 2.00475624,  3.16765755,  5.55053508])

In [23]:
prototypesRF = []
for signal in prototypeSignals:
    prototypesRF.append(signal.get_poi('RightFemur'))

In [24]:
np.var(np.array(prototypesRF),axis = 0)

array([ 2.57074911,  4.32580262,  4.22592152])

In [10]:
testSignal.y_offset

-194.19644165039062