In [14]:
from os import listdir
from os.path import isfile, join
import os
import numpy as np
from amrafile import amrafile as af
from amracommon.analysis.registration import normalized_cross_correlation
from scipy.ndimage import gaussian_filter, sobel
import matplotlib.pyplot as plt

testTargets = ["00010","00011","00012","00013","00014","00015","00016","00018","00019",
                "0000B","0000C","0000D","0000E","0003A","0003B","0003C","0001A","0001B",
                "00025","0003D","0003E","0003F","00033","00034","00035","00036","00037",
                "00038","00039","00040","00041","00042","00043","00044","00045","00046",
                "00047","00048","00049","0004A","0004B","0004C","0004D","0004E","0004F",
                "00050","00051"]

diffZ, diffY, diffX = np.zeros((2,len(testTargets))), np.zeros((2,len(testTargets))), np.zeros((2,len(testTargets)))

for k, target in enumerate(testTargets):

    signal = af.parse('/moria/data/DB/0064/'+target+'/wholebody_normalized_water_1_'+target+'.amra')
    
    voxelSize = signal.voxel_size()
    
    RF = np.array(signal.get_poi('RightFemur'))*voxelSize
    S1 = np.array(signal.get_poi('S1'))*voxelSize
    #L5 = np.array(signal.get_poi('L5'))*voxelSize
    #L4 = np.array(signal.get_poi('L4'))*voxelSize
    #L3 = np.array(signal.get_poi('L3'))*voxelSize
    #L2 = np.array(signal.get_poi('L2'))*voxelSize
    #L1 = np.array(signal.get_poi('L1'))*voxelSize
    #T12 = np.array(signal.get_poi('T12'))*voxelSize
    #T11 = np.array(signal.get_poi('T11'))*voxelSize
    #T10 = np.array(signal.get_poi('T10'))*voxelSize
    #T9 = np.array(signal.get_poi('T9'))*voxelSize
    
    #poiList = np.array([LF,S1,L5,L4,L3,L2,L1,T12,T11,T10,T9])
    poiList = np.array([RF,S1])
    
    shiftList = np.roll(poiList,-1, axis=0)
    
    diff = poiList - shiftList
    
    diffZ[:,k] = diff[:,0]
    diffY[:,k] = diff[:,1]
    diffX[:,k] = diff[:,2]

meanList = list(zip(np.mean(diffZ,1), np.mean(diffY,1), np.mean(diffX,1)))
stdList = list(zip(np.std(diffZ,1), np.std(diffY,1),  np.std(diffX,1)))


In [15]:
meanList

[(-75.480687127056939, -36.933857298911889, -89.211292058863535),
 (75.480687127056939, 36.933857298911889, 89.211292058863535)]

In [56]:
stdList

[(7.9951211792962278, 9.0559172426420051, 5.1655986029923122),
 (4.9813529092421103, 5.0376726160220588, 2.5377478596237877),
 (2.7881078545832323, 4.1596186702135958, 2.6655734738253445),
 (2.3816767236319194, 3.8590082080463843, 2.2991701861924656),
 (2.7127559588853991, 2.6704307725087526, 2.5086490150553247),
 (2.1449822614303717, 2.2518108896468165, 2.1486495031368023),
 (3.4598809163381832, 3.0513714572490329, 1.8380497064521508),
 (2.6441732157579692, 2.4613374777841641, 1.4611047073405119),
 (2.0603591707117248, 2.2930031439292606, 1.4239883136486764),
 (2.7730728559214972, 2.5200168433051919, 1.6335269704859403),
 (16.241536169731667, 9.233075987563085, 10.266163370305865)]

In [45]:
meanList

[(-36.836035662622905, 24.527422357112805, -0.55779665581723481),
 (-35.922162073098939, 2.4083386583531157, -0.039179624395167575),
 (-36.326124999316825, -3.8100721125907087, 0.96694531339280154),
 (-34.795591430906633, -7.8516734052211676, -0.081448935447855197),
 (-32.988777130392975, -8.0378436281325971, 0.29825228833137674),
 (-31.755978362047777, -7.1924788647509637, 0.03657021421067258),
 (-29.204915661108412, -4.6371538892705386, 0.28091702055423817),
 (-27.036933512500138, -3.2950207426192915, -0.085486320739096788),
 (-24.635255042947769, -2.6322647916509752, -0.29279118903139806),
 (289.50177387494227, 10.520746418770324, -0.52598211105833659)]

In [47]:
stdList

[(4.9813529092421103, 5.0376726160220588, 2.5377478596237877),
 (2.7881078545832323, 4.1596186702135958, 2.6655734738253445),
 (2.3816767236319194, 3.8590082080463843, 2.2991701861924656),
 (2.7127559588853991, 2.6704307725087526, 2.5086490150553247),
 (2.1449822614303717, 2.2518108896468165, 2.1486495031368023),
 (3.4598809163381832, 3.0513714572490329, 1.8380497064521508),
 (2.6441732157579692, 2.4613374777841641, 1.4611047073405119),
 (2.0603591707117248, 2.2930031439292606, 1.4239883136486764),
 (2.7730728559214972, 2.5200168433051919, 1.6335269704859403),
 (15.585853285558665, 9.3023152298626908, 8.2941252563127552)]

In [12]:
shiftList

array([[ 263.39286518,  258.92857933,  569.22764228],
       [ 243.30357885,  261.16072226,  605.17886179],
       [ 238.839293  ,  261.16072226,  641.1300813 ],
       [ 241.07143593,  256.69643641,  677.08130081],
       [ 243.30357885,  254.46429348,  710.03658537],
       [ 250.00000763,  252.23215055,  742.99186992],
       [ 254.46429348,  247.7678647 ,  775.94715447],
       [ 258.92857933,  247.7678647 ,  805.90650407],
       [ 263.39286518,  250.00000763,  829.87398374],
       [ 267.85715103,  247.7678647 ,  533.27642276]])

In [2]:
import numpy as np

In [4]:
a = np.load('/media/hannes/localDrive/trained/scalar/T9/test5/error.npy')

In [5]:
b = np.load('/media/hannes/localDrive/trained/scalar/T9/test5/inliers.npy')

In [178]:
c = list(a[:,1])

In [179]:
np.mean(b)

8.6724446795950048

In [180]:
np.median(b)

7.0234415676303401

In [181]:
np.max(b)

137.33716416607999

In [182]:
poi_index = b.index(max(b))    

In [183]:
b.pop(poi_index)

137.33716416607999

In [184]:
np.mean(b)

7.5727462224455611

In [185]:
np.std(b)

3.8485702604937182

In [186]:
np.amax(b)

22.127591557600471

In [187]:
np.median(b)

6.988227428400335

In [111]:
c = np.load('/media/hannes/localDrive/trained/scalar/LeftFemur/test28/error.npy')

In [112]:
c = list(c[:,1])

In [113]:
poi_index = c.index(max(c)) 

In [114]:
c.pop(poi_index)

137.33716416607999

In [115]:
np.mean(c)

7.667547561469644

In [116]:
np.std(c)

3.8379323749000758

In [109]:
np.amax(c)

14.4317049523825

In [45]:
sad = np.load('/home/hannes/code/git/T9/reg.npy')

In [46]:
sad

array([[  4.46428585,   3.1567268 ,   2.23214293,   3.1567268 ,
          4.46428585,   6.69642878,   3.1567268 ,   6.69642878,
          4.35207426,   2.23214293,   4.46428585],
       [  7.47210502,   3.1567268 ,   4.46428585,   5.37638117,
          4.46428585,   4.99122332,   3.73605251,   3.73605251,
          7.47210502,  12.18985164,  21.90126447],
       [  5.37638117,   5.8213346 ,   8.58764419,   7.05865571,
          9.20336105,   4.46428585,   4.99122332,   4.46428585,
          7.05865571,   8.04810577,  18.02557285],
       [  2.99593496,   4.35207426,   3.73605251,   4.46428585,
          4.35207426,   8.04810577,   2.23214293,   5.8213346 ,
          5.8213346 ,   8.04810577,   7.66813189],
       [  5.37638117,  19.99145335,  10.98200163,   5.37638117,
          4.99122332,   0.        ,   2.23214293,   9.25889441,
          3.73605251,   3.73605251,   4.35207426],
       [  4.35207426,   3.1567268 ,   4.35207426,   6.69642878,
          3.1567268 ,   8.9285717 ,   6.6

In [48]:
sad = np.delete(sad, (1), axis=0)

In [51]:
np.mean(sad,0)

array([ 5.0861454 ,  8.07621939,  6.26335858,  4.41409359,  3.83106654,
        6.36258126,  4.04096088,  5.08555892,  4.62791717,  4.49685441,
        5.1355285 ])

In [52]:
np.std(sad,0)

array([ 1.42904257,  5.56971857,  3.12283992,  2.4491917 ,  0.91693364,
        4.02210474,  1.65752068,  2.14649803,  0.80790516,  2.09951282,
        1.71924584])

In [20]:
sad[:,0]

array([  4.46428585,  21.90126447,  18.02557285,   7.66813189,
         4.35207426,   7.05865571,   4.35207426,   5.8213346 ,   2.23214293])

In [23]:
dtd = list(sad[:,0])

In [25]:
dtd.pop(2)

18.025572851815234

In [27]:
dtd.pop(1)

21.90126446579297

In [29]:
np.mean(dtd)

5.1355284992584656

In [30]:
np.std(dtd)

1.7192458383102343