In [1]:
import numpy as np
import random
import amrafile.amrafile as af
from amracommon.analysis.registration import normalized_cross_correlation

In [5]:
import matplotlib.pyplot as plt

In [20]:
signal = af.parse('/moria/data/DB/0064/00017/wholebody_normalized_water_1_00017.amra')

In [12]:
signal2 = af.parse('/moria/data/DB/0030/0014C/wholebody_normalized_water_1_0014C.amra')

In [13]:
normalized_cross_correlation(signal.data, signal2.data)

AssertionError: Shapes must match

In [21]:
signal.get_pois()

[((151, 87, 76), 'RightFemur'),
 ((151, 89, 160), 'LeftFemur'),
 ((276, 112, 112), 'T9')]

In [7]:
rf = signal.get_poi('Manubrium')

In [16]:
signal.voxel_size()

(2.9959349593495936, 2.2321429252624512, 2.2321429252624512)

In [17]:
(signal.data).shape

(330, 174, 224)

In [8]:
plt.figure(frameon =False)
currentAxis = plt.gca()
plt.imshow((signal.data[:, rf[1],:]), plt.get_cmap('gray'), origin='lower')
plt.autoscale(False)
plt.plot(rf[2], rf[0], marker='o', color='g')

plt.show()

In [19]:
np.random.normal(1, 2, 3)

array([-0.51678452, -0.47499936, -2.52268895])

In [20]:
a = np.array([(1,2,3),(1,2,4)])

In [21]:
a = [1,2,3]

In [22]:
a = zip(a)

In [23]:
a

In [24]:
list(a)[0]

(1,)

In [25]:
b = [[1,2,3],]

In [26]:
for lists in b:
    print(lists)

[1, 2, 3]


In [27]:
a = np.random.randn(2,2,2)

In [28]:
target_size = [5,5,5]

In [29]:
z_grid, y_grid, x_grid = np.mgrid[0:target_size[0], 0:target_size[1], 0:target_size[2]]

grids = [z_grid, y_grid, x_grid]

In [ ]:
poi = [0,0,0]

In [ ]:
a = [(grids[ind] - pos) for ind, pos in enumerate(poi)]

In [ ]:
b = a.copy()

In [ ]:
c = list(zip(a,b))

In [ ]:
np.shape(np.transpose(np.vstack([np.ravel(c[1][1]),np.ravel(c[0][1])])))

In [31]:
np.shape(grids)

(3, 5, 5, 5)

In [32]:
np.shape(grids[0])

(5, 5, 5)

In [37]:
a = np.vstack((grids[0],grids[1]))

In [38]:
np.shape(a)

(10, 5, 5)

In [85]:
grids[0]

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]])

In [41]:
a = np.random.randn(2,2,2)

In [42]:
b = np.random.randn(2,2,2)

In [43]:
a

array([[[ 1.26232458, -1.62372781],
        [-0.23488012,  0.53047335]],

       [[ 1.82386384, -1.77875145],
        [-1.06891497,  0.22162887]]])

In [44]:
b

array([[[-0.64227142,  0.95894653],
        [-0.93935341, -0.02488068]],

       [[-0.93058531,  0.702275  ],
        [-0.33584227,  0.83505509]]])

In [46]:
c = np.vstack((a,b))

In [48]:
c[0,1]

array([-0.23488012,  0.53047335])

In [97]:
grids[0]

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]])

In [71]:
a = np.vstack((grids[0],grids[1]))

In [96]:
X_train = grids[0]

In [87]:
y_train = np.array(range(5))

In [88]:
y_train

array([0, 1, 2, 3, 4])

In [65]:
        voxel_size = [2,3,3]
        target_poi = [5,3,6]
        target_size = [10,10,10]

        z_upper = target_size[0]-target_poi[0]
        z_lower = target_size[0]-z_upper
        y_upper = target_size[1]-target_poi[1]
        y_lower = target_size[1]-y_upper
        x_upper = target_size[2]-target_poi[2]
        x_lower = target_size[2]-x_upper
        
        ''' Extract arrays containing voxel distances to the target poi position '''
        z_voxel_dist, y_voxel_dist, x_voxel_dist = np.mgrid[-z_lower:z_upper,-y_lower:y_upper,-x_lower:x_upper]

        ''' Express in milimeters according to voxel sizes '''
        voxel_dist = [z_voxel_dist, y_voxel_dist, x_voxel_dist]

In [107]:
np.shape(z_voxel_dist[:,0,0])

(10,)

In [105]:
from sknn.mlp import Regressor, Convolution, Layer

nn = Regressor(
    layers=[
        Convolution("Rectifier", channels=10, kernel_shape=(2,2)),
        Layer("Linear")],
    learning_rate=0.02,
    n_iter=100)
nn.fit(X_train, y_train)

/home/hannes/.virtualenvs/devel/lib/python3.4/site-packages/lasagne/layers/conv.py:489: UserWarning: The `image_shape` keyword argument to `tensor.nnet.conv2d` is deprecated, it has been renamed to `input_shape`.
  border_mode=border_mode)


Regressor(batch_size=1, callback=None, debug=False, dropout_rate=None,
     f_stable=0.001,
     hidden0=<sknn.nn.Convolution `Rectifier`: name='hidden0', kernel_stride=(1, 1), scale_factor=(1, 1), border_mode='valid', frozen=False, pool_shape=(1, 1), kernel_shape=(2, 2), channels=10>,
     layers=[<sknn.nn.Convolution `Rectifier`: name='hidden0', kernel_stride=(1, 1), scale_factor=(1, 1), border_mode='valid', frozen=False, pool_shape=(1, 1), kernel_shape=(2, 2), channels=10>, <sknn.nn.Layer `Linear`: name='output', units=1, frozen=False>],
     learning_momentum=0.9, learning_rate=0.02, learning_rule='sgd',
     loss_type=None, n_iter=100, n_stable=10, normalize=None,
     output=<sknn.nn.Layer `Linear`: name='output', units=1, frozen=False>,
     parameters=None, random_state=None, regularize=None, valid_set=None,
     valid_size=0.0, verbose=None, warning=None, weight_decay=None)

In [106]:
nn.predict(grids[0])

array([[ 0.08055219],
       [ 2.5085973 ],
       [ 2.5085973 ],
       [ 2.5085973 ],
       [ 2.5085973 ]])

In [108]:
np.shape(grids[0])

(5, 5, 5)

In [121]:
d = np.random.randn(4,3,2)

In [126]:
e = np.vstack((d,d))

In [127]:
np.shape(e)

(8, 3, 2)

In [18]:
test = [np.random.randn(2,2,3) for i in range(0,3)]

In [16]:
np.array(test)/np.array([10,100,1000])

ValueError: operands could not be broadcast together with shapes (3,3,4,4) (3,) 

In [58]:
f = np.round(np.random.randn(10,3)).astype(int)

In [55]:
k = list(zip(f[:,0],f[:,1],f[:,2]))

In [56]:
np.array(max(set(k), key=k.count))

array([1, 0, 1])

In [57]:
k

[(0, 1, 1),
 (0, 0, 0),
 (1, 0, 1),
 (2, -1, 1),
 (0, 0, 0),
 (1, 1, -1),
 (0, -1, 0),
 (1, 0, 0),
 (1, 0, 1),
 (-1, 0, 0)]

In [60]:
f/np.array([10,100,1000])

array([[ 0.   ,  0.02 , -0.001],
       [-0.1  , -0.01 ,  0.002],
       [-0.1  ,  0.   ,  0.   ],
       [ 0.1  ,  0.   , -0.001],
       [ 0.   ,  0.01 ,  0.002],
       [ 0.1  ,  0.01 ,  0.   ],
       [ 0.2  ,  0.01 ,  0.002],
       [-0.1  ,  0.02 , -0.001],
       [ 0.1  ,  0.   , -0.002],
       [ 0.   ,  0.   ,  0.   ]])