In [13]:
import numpy as np
import random
import amrafile.amrafile as af

In [18]:
import matplotlib.pyplot as plt

In [87]:
signal = af.parse('/moria/data/DB/0030/00149/wholebody_normalized_water_1_00149.amra')

In [88]:
signal.get_pois()

[((154, 101, 140), 'LeftFemur'),
 ((155, 102, 70), 'RightFemur'),
 ((272, 122, 107), 'T9')]

In [89]:
rf = signal.get_poi('LeftFemur')

In [90]:
plt.figure(frameon =False)
currentAxis = plt.gca()
plt.imshow((signal.data[:, rf[1],:]), plt.get_cmap('gray'), origin='lower')
plt.autoscale(False)
plt.plot(rf[2], rf[0], marker='o', color='g')

plt.show()

In [131]:
a = np.random.randint(5,size=(2,3))

In [132]:
print(a)

[[2 1 2]
 [2 4 1]]


In [133]:
b = np.random.randint(5,size=(2,3))

In [134]:
print(b)

[[0 1 0]
 [3 3 1]]


In [135]:
c = list(zip(a,b))

In [136]:
c

[(array([2, 1, 2]), array([0, 1, 0])), (array([2, 4, 1]), array([3, 3, 1]))]

In [170]:
len(c)

2

In [168]:
asd =np.array([c[ind][0] for ind in range(2)])

In [169]:
asd

array([[2, 1, 2],
       [2, 4, 1]])

In [138]:
e = [1,2,3]

In [139]:
f = [3,2,1]

In [146]:
g = list(zip(*[e,f]))

In [147]:
g

[(1, 3), (2, 2), (3, 1)]

In [148]:
g[0]

(1, 3)

In [151]:
[g[i][1] for i in range(3)]

[3, 2, 1]

In [152]:
len(g)

3